### ISSUE TITLE
World map responsiveness - adjust size to browser window size

### ISSUE THREAD

**Issue by Quintin-Yu** [ConclusionNL/global-mitigation-potential-atlas#34]
EDIT by Mike:

Worldmap height and width gets determined when the page gets rendered. These values should be responsive when the page changes size. Currently the product is only working 'correctly' when the page loads in with the full browser width & height (minimal 1920x1080 for a visual decent look).

**Comment by lucasjellema** [comment]
we have to make the size of the svg element that contains the worldmap depend on the screen size instead of having it fixed . 

Ideally we should also redraw the map when the browser window size has changed - to adapt to the new situation.

other SVG objects should also resize in case of smaller browser window sizes.

**Comment by lucasjellema** [comment]
fixed along with #88

**Comment by Quintin-Yu** [comment]
As it is fixed in a previous issue I will now close this issue. @lucasjellema
