### ISSUE TITLE
Remove Brunei from set of supported pilot countries

### ISSUE THREAD

**Issue by xavierroosendaal** [ConclusionNL/global-mitigation-potential-atlas#98]
Some countries may or may not be included in a state of the world map. While we do not want to remove all the data and options of a country and possibly re-enter them later, it would be easier to have a toggle to turn countries on/off.

This would mean that:

![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/146175180/1a4f22b5-f21a-4d57-a68b-5274ee69eadf)

- [x] Country does not show in the sidebar

![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/146175180/52b90464-0f73-4826-ae77-621cf0c786c9)

- [x] Country does not show in suggestions for collaboration

![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/146175180/d0232cd8-931d-4d64-a9f2-ea5a9fca9982)

- [x] Country does not show up in national policies

**Comment by xavierroosendaal** [comment]
- [ ] Toggle brunei off

**Comment by lucasjellema** [comment]
I am not sure what the actual requirement in this issue is. Do we have to make sure that Brunei is no longer presented as a country in the pilot set?

Is there a more generic requirement? I am not sure "toggle certain countries on/off" means. what are these countries? or is the request to somehow make it possible - not going through software developers - to include/exclude a country? If that is the case, I am wondering why? When would that be used and by whom and how often? A simple ticket to request a country to be added or removed may be an easier way of resolving this and trying to build a generic mechanism.

An intermediate step: we define a data file (included-countries.csv) that contains the list of countries that is to be included (whatever that means exactly). CA can upload new versions of that data file and we can include it in GMPA. Would that work?

**Comment by xavierroosendaal** [comment]
Yes, the intention is to no longer 'include' Brunei as a country in the pilot set. For now this is the only country. However, maybe later (december) the country should be included again. It would be easier for the developers and editors to have to toggle a country off/on instead of needing to re-enter data, code etc. Making adding/removing countries modular might be less effort than adding/removing by hand everytime.

This would not have to be a toggle for the website (users).

When that would be used: when the set of countries need to change for whatever reason. How often: hard to say, maximum a few times, 

Impact/effort on what step to take is important. Not sure how difficult this toggle is. A data file or a ticket might just as well work if that makes sure we remove/add a country on every single page as I tried to showcase with the screenshot.

**Comment by lucasjellema** [comment]
I think the toggle is not a simple thing. If it is only for a few countries, I would stick to a manual procedure.

Note: Countries for which we have no (collaboration) data do not show up in the suggested collaboration partner - so that aspect is already taken care of.

**Comment by lucasjellema** [comment]
@Quintin-Yu  the issue becomes simply: remove Brunei from this list of countries shown in the sidebar, in the dropdown and probably in the search bar.

**Comment by Quintin-Yu** [comment]
Removing a country from everything should be fairly easy as most logic is based on if the country is active in Umbraco I'll disable it right now in the Accept and Test environments.

If there is more work I'll send a new comment

**Comment by Quintin-Yu** [comment]
Dropdown has been fixed now but is hard coded. See changes on the Test environment

**Comment by OmNomNomzzz** [comment]
We will need to update the Brunei modelling data (csv) and country write up in December. We will then need to enable Brunei. A simple toggle just for Brunei as Quintin described solves the issue. If the toggle enables/ disables Brunei, then we can close the issue.

**Comment by lucasjellema** [comment]
@Quintin-Yu can you describe the exact steps we need to take to enable Brunei (and indeed any other country)?

* do something somewhere in Umbraco (please describe wat, where and how)
* do something with the contents of the dropdownlist (this sounds like code: in what file should be done what exactly?)
* how do we get these changes to T/A and P? (especially the change in Umbraco)

ideally the description has screenshots (because one picture > 1000 words)

perhaps we can start documentation as code in markdown files as part of the git repo for describing the code base and ops/maintenance tasks like this one

**Comment by xavierroosendaal** [comment]
My intention is to write some general documentation on how we use github projects as a WoW, I do not know where to share this yet, but if we combine documentation efforts in 1 location that sounds effecient to me,

**Comment by Quintin-Yu** [comment]
@lucasjellema Currently all you need to do is click the switch in my previous comment on how to disable a country to enable it again and show it in the sideNav and allow it functionality through the searchBar. In the Cases page, I created a dropdown for country filtering this one was hard coded. Tomorrow I am going to look into making this dynamic so that all that needs to be done is flick a switch in Umbraco to change if a country is active or not.

Since we have set-up the DTAP a country needs to be disabled in the Accept environment. Everything that has to be done through Umbraco when it comes to content should be done in the Accept environment. All Content that has been changed in Umbraco in the Test environment is NOT sent over to the Accept environment.

So:
- Q: do something somewhere in Umbraco (please describe wat, where and how)
- Q: do something with the contents of the dropdownlist (this sounds like code: in what file should be done what exactly?)
- Q: how do we get these changes to T/A and P? (especially the change in Umbraco)

**Comment by Quintin-Yu** [comment]
Closed on accident :)

**Comment by Quintin-Yu** [comment]
Dropdown is no longer hard coded as of issue #102

**Comment by OmNomNomzzz** [comment]
@noni-12 Please review this and close issue if this is resolved.

**Comment by noni-12** [comment]
Brunei removed from country list drop down in the national policy page
